name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker with Minikube
      run: eval $(minikube docker-env)

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push backend image
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/shape-up-backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/shape-up-backend:latest

    - name: Build and push frontend image
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/shape-up-frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/shape-up-frontend:latest

    - name: Create namespace
      run: kubectl create namespace shape-up --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to Minikube
      run: kubectl apply -f k8s/
